package com.app.livrizon.model.response

enum class ResponseState {
    DENIED, INCORRECT_TOKEN_SIGN, INCORRECT_TOKEN, TOKEN_EXPIRED, INCORRECT_TOKEN_TYPE, ACCESS, ALREADY_EXIST, ALREADY_CONTAIN,
    EXIST, NOT_EXIST, NOT_CONTAIN, CODE_SEND, EXCEPTION, SUCCESS, EMPTY, FILE_ERROR, TOKEN_EXCEPTION, TYPE_ERROR,
    YOURSELF, LENGTH_TITTLE_ERROR, NO_ACTIVE, INCORRECT_DATE, PARAM_NOT_VALID, ATTEMPT_LIMIT, INCORRECT_EDUCATION_DATA, SKILL_ERROR,
    RESUME_ERROR, EMPTY_TITLE, EMPTY_DESCRIPTION, INCORRECT_ADDRESS, INCORRECT_SALARY, EMPTY_EMPLOYMENT, EMPTY_CHART, EMPTY_CURRENCY,
    INCORRECT_DATA, DATA_EXCEPTION
}